spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: boot-auth
          uri: lb://boot-auth
          predicates:
           - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
        #UPMS 模块
        - id: boot-upms
          uri: lb://boot-upms
          predicates:
           - Path=/admin/**
