## 数据库连接池
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://boot-mysql:3306/boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ENC(y0MVSykTX0iVSqMpaGusFA==)
    password: ENC(VMgWiFR16g8bFGkUo0oZ9A==)
    type: com.zaxxer.hikari.HikariDataSource

## security 配置
security:
  oauth2:
    client:
      client-id: test
      client-secret: test
      scope: server
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /virtualaddress/download/*




com:
  alibaba:
    nacos:
      config:
        log:
          level: warn
      naming:
        log:
          level: warn