## 数据库连接池
spring:
  dynamic:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.104.172.27:3306/boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: ENC(y0MVSykTX0iVSqMpaGusFA==)
      password: ENC(VMgWiFR16g8bFGkUo0oZ9A==)
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: ENC(y0MVSykTX0iVSqMpaGusFA==)
      password: ENC(TNa/fF1g0RJ39k80QKSQLPpAr1E8oqPZ)
    

## security 配置
security:
  oauth2:
    client:
      client-id: test
      client-secret: test
      scope: server
      ignore-urls:
        - /actuator/**
        - /user/info/*
        - /mobile/**
        - /ws/**
        - /v2/api-docs
        - /social/info/*
        - /route
        - /log/**

## 七牛云配置
oss:
  name: qiniu
qiniu:
  accessKey: 3QwcYlLnnsmKAb_y2thYWhMthLnLJE4BhgEg5CMP
  secretKey: VbTcSVpXEyGkUCo2WEdVnzT3mnqWn0gtnXde9sBU
  bucket: ceshieva
  path: http://pw625v2wl.bkt.clouddn.com/


