## spring security 配置
security:
  oauth2:
    client:
      client-id: test
      client-secret: test
      scope: server

## 定时任务
spring:
  dynamic:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.104.172.27:3306/boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: ENC(y0MVSykTX0iVSqMpaGusFA==)
      password: ENC(VMgWiFR16g8bFGkUo0oZ9A==)
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: ENC(y0MVSykTX0iVSqMpaGusFA==)
      password: ENC(TNa/fF1g0RJ39k80QKSQLPpAr1E8oqPZ)
  elasticjob:
    # 分布式任务协调依赖zookeeper
    zookeeper:
      server-lists: boot-zookeeper:2181
      namespace: boot-daemon
    # 普通任务
    simples:
      spring-simple-job:
        job-class: com.study.boot.daemon.job.PigxSimpleJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.study.boot.daemon.listener.PigxElasticJobListener
      spring-simple-job2:
        job-class: com.study.boot.daemon.job.PigxSimpleJob2
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.study.boot.daemon.listener.PigxElasticJobListener
    # 简单任务
    dataflows:
      spring-dataflow-job:
        job-class: com.study.boot.daemon.job.PigxDataflowJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        streaming-process: true
        eventTraceRdbDataSource: 'dataSource'
        listener:
          distributed-listener-class: com.study.boot.daemon.listener.PigxDistributeElasticJobListener
          started-timeout-milliseconds: 5000
          completed-timeout-milliseconds: 10000


