spring:
  autoconfigure:
    exclude: org.flowable.spring.boot.FlowableSecurityAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(y0MVSykTX0iVSqMpaGusFA==)
    password: ENC(VMgWiFR16g8bFGkUo0oZ9A==)
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://boot-mysql:3306/flowable-boot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8

## security 配置
security:
  oauth2:
    client:
      client-id: test
      client-secret: test
      scope: server
      ignore-urls:
        - /actuator/**
        - /service/**
        - /editor-app/**
        - /v2/api-docs
        - /task/view/*
        - /process/resource/**
        - /modeler.html


flowable:
  check-process-definitions: false


com:
  alibaba:
    nacos:
      config:
        log:
          level: warn
      naming:
        log:
          level: warn