version: '2'

services:
  gitlab:
    image: twang2218/gitlab-ce-zh:10.5
    restart: always
    hostname: gitlab
    container_name: gitlab
    ports:
      - '9110:443'
      - '9111:80'
      - '9112:22'
      - '9113:9090'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab