version:  '2'

services:
  fastdfs:
    image: sjqzhang/go-fastdfs
    restart: always
    container_name: fastdfs
    environment:
      GO_FASTDFS_DIR: /data
    volumes:
      - ./data/fastdfs_data:/data
