server:
  port: 8081

## spring 配置文件配置
spring:
  application:
    name: boot-gateway
  profiles:
    active: dev
  cloud:
#    config:
#      fail-fast: true
#      name: ${spring.application.name}
#      profile: ${spring.profiles.active}
#      discovery:
#        enabled: true
#        service-id: boot-config

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: boot-auth
          uri: lb://boot-auth
          predicates:
            - Path=/auth/**
        #UPMS 模块
        - id: boot-upms
          uri: lb://boot-upms
          predicates:
            - Path=/admin/**

## 注冊中心配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:9999/eureka/


