server:
  port: 8081

## spring 配置文件配置
spring:
  application:
    name: boot-gateway
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: boot-config
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

## 注冊中心配置


