version: '2'
services:
  prometheus:
    image: prom/prometheus:v2.10.0
    container_name: prometheus
    command: --config.file=//etc/prometheus/prometheus.yml --log.level=info
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml